### ISSUE TITLE
requires bower-asset/moment 2.* -> no matching package found.

### ISSUE THREAD

**Issue by ivantree** [zhuravljov/yii2-datetime-widgets#5]
Problem 1
    - zhuravljov/yii2-datetime-widgets dev-master requires bower-asset/moment 2.* -> no matching package found.

**Comment by zhuravljov** [comment]
Yii2 application depends form `composer-asset-plugin`. It enables to pull the bower packages through composer.
You need to execute:

```bash
php composer.phar global require "fxp/composer-asset-plugin:1.0.0"
```
[More details](https://github.com/yiisoft/yii2-app-basic#install-via-composer)

After installing it, composer going to pull bower packages.

**Comment by ivantree** [comment]
yeh.ths
